"""PyMuPDF helpers for signed contract PDF and demo audit certificate."""
from __future__ import annotations

import hashlib
import io
from datetime import datetime, timezone

import fitz

from ..models import Contract, SignatureField, SignatureRequest, SignatureSigner, SignatureEvent
from .storage import storage

DEMO_FOOTER_EN = (
    "Demo electronic signature generated by ContractOps AI. "
    "Not represented as a certified trust-service signature."
)
DEMO_FOOTER_AR = (
    "توقيع إلكتروني تجريبي تم إنشاؤه عبر ContractOps AI، "
    "ولا يُمثّل توقيعًا معتمدًا من مقدم خدمات ثقة مرخص."
)


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def original_bytes(contract: Contract) -> bytes:
    if not contract.file_url:
        return _demo_text_pdf(contract.title or "Contract", contract.raw_text or "")
    raw = storage.get(contract.file_url)
    if raw[:4] == b"%PDF":
        return raw
    text = contract.raw_text or contract.title or "Contract document"
    return _demo_text_pdf(contract.title or "Contract", text)


def _demo_text_pdf(title: str, body: str) -> bytes:
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    page.insert_text((50, 50), title[:200], fontsize=14)
    page.insert_text((50, 80), "Demo PDF representation (original upload was not PDF).", fontsize=10)
    chunk = (body or "")[:8000]
    page.insert_textbox(fitz.Rect(50, 110, 545, 800), chunk, fontsize=9)
    out = doc.tobytes()
    doc.close()
    return out


def _load_signature_image(signer: SignatureSigner) -> bytes | None:
    if not signer.signature_value_url:
        return None
    try:
        return storage.get(signer.signature_value_url)
    except Exception:
        return None


def _append_legacy_signature_page(doc: "fitz.Document", request: SignatureRequest, signers: list[SignatureSigner]) -> None:
    """Pre-field-placement fallback: appends a summary page listing every
    signer and their captured mark, stacked vertically. Kept only for
    signature requests created before signature_fields existed (no rows
    persisted for them) so old/legacy signed PDFs can still be
    regenerated/read — every request created going forward has real fields
    and is embedded in place via build_signed_pdf's main path below."""
    page = doc.new_page(width=595, height=842)
    y = 40
    page.insert_text((40, y), "Signatures / التوقيعات", fontsize=16)
    y += 30
    page.insert_text((40, y), f"Request: {request.id}", fontsize=9)
    y += 24
    for s in sorted(signers, key=lambda x: x.signer_order):
        page.insert_text((40, y), f"{s.signer_order}. {s.name} — {s.role}", fontsize=11)
        y += 16
        if s.signed_at:
            page.insert_text((40, y), f"Signed: {s.signed_at.isoformat()}", fontsize=9)
            y += 14
        img = _load_signature_image(s)
        if img and (img[:4] == b"\x89PNG" or img[:2] == b"\xff\xd8"):
            try:
                rect = fitz.Rect(40, y, 240, y + 60)
                page.insert_image(rect, stream=img)
                y += 70
            except Exception:
                if s.signature_type == "typed" and signer_text_from_storage(s):
                    page.insert_text((40, y), signer_text_from_storage(s) or "", fontsize=14)
                    y += 24
        elif s.signature_type == "typed":
            txt = signer_text_from_storage(s)
            if txt:
                page.insert_text((40, y), txt, fontsize=16)
                y += 28
        y += 10
    y = min(y + 20, 780)
    page.insert_text((40, y), DEMO_FOOTER_EN, fontsize=8)
    page.insert_text((40, y + 14), DEMO_FOOTER_AR, fontsize=8)


def _initials_for(name: str) -> str:
    parts = [p for p in (name or "").split() if p]
    return "".join(p[0] for p in parts)[:4].upper() or "—"


def build_signed_pdf(
    contract: Contract,
    request: SignatureRequest,
    signers: list[SignatureSigner],
    fields: list[SignatureField] | None = None,
) -> bytes:
    """Embeds each signer's mark at the exact page/coordinates confirmed in
    signature_fields — signature image or typed text for `signature`
    fields, and deterministic values for `initials`/`name`/`date` fields.
    Falls back to the old "append a summary page" behavior only when a
    request has no persisted fields at all (legacy requests predating this
    fix — see _append_legacy_signature_page)."""
    base = original_bytes(contract)
    doc = fitz.open(stream=base, filetype="pdf")
    fields = fields or []

    by_signer: dict[str, list[SignatureField]] = {}
    for f in fields:
        by_signer.setdefault(str(f.signer_id), []).append(f)

    placed_any = False
    for s in sorted(signers, key=lambda x: x.signer_order):
        signer_fields = by_signer.get(str(s.id), [])
        if not signer_fields or not s.signed_at:
            continue
        img = _load_signature_image(s)
        typed_text = signer_text_from_storage(s) if s.signature_type == "typed" else None
        for f in signer_fields:
            page_index = max(0, min(int(f.page_number) - 1, doc.page_count - 1))
            page = doc[page_index]
            rect = fitz.Rect(
                float(f.x) * page.rect.width,
                float(f.y) * page.rect.height,
                (float(f.x) + float(f.width)) * page.rect.width,
                (float(f.y) + float(f.height)) * page.rect.height,
            )
            placed_any = True
            if f.field_type == "signature":
                placed = False
                if img and (img[:4] == b"\x89PNG" or img[:2] == b"\xff\xd8"):
                    try:
                        page.insert_image(rect, stream=img)
                        placed = True
                    except Exception:
                        placed = False
                if not placed and typed_text:
                    page.insert_textbox(rect, typed_text, fontsize=14)
            elif f.field_type == "initials":
                page.insert_textbox(rect, _initials_for(s.name), fontsize=12)
            elif f.field_type == "name":
                page.insert_textbox(rect, s.name, fontsize=10)
            elif f.field_type == "date":
                page.insert_textbox(rect, s.signed_at.date().isoformat(), fontsize=9)

    if not placed_any:
        _append_legacy_signature_page(doc, request, signers)
    else:
        # Keep the demo disclosure visible without overlapping a placed
        # field — stamp it small in a corner of the last page rather than
        # appending a whole new page.
        last = doc[-1]
        last.insert_text((20, last.rect.height - 24), DEMO_FOOTER_EN[:130], fontsize=6)
        last.insert_text((20, last.rect.height - 14), DEMO_FOOTER_AR[:130], fontsize=6)

    out = doc.tobytes()
    doc.close()
    return out


def signer_text_from_storage(signer: SignatureSigner) -> str | None:
    if signer.signature_type != "typed" or not signer.signature_value_url:
        return None
    try:
        return storage.get(signer.signature_value_url).decode("utf-8")
    except Exception:
        return None


def build_certificate_pdf(
    contract: Contract,
    request: SignatureRequest,
    signers: list[SignatureSigner],
    events: list[SignatureEvent],
    *,
    original_hash: str,
    signed_hash: str,
) -> bytes:
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    y = 40
    page.insert_text((40, y), "Demo Signature Audit Certificate", fontsize=16)
    page.insert_text((40, y + 18), "شهادة سجل توقيع تجريبية", fontsize=14)
    y += 50
    lines = [
        f"Contract: {contract.title}",
        f"Contract ID: {contract.id}",
        f"Signature Request ID: {request.id}",
        f"Provider: {request.provider}",
        f"Created: {request.created_at}",
        f"Sent: {request.sent_at}",
        f"Completed: {request.completed_at}",
        f"Original hash (SHA-256): {original_hash}",
        f"Signed hash (SHA-256): {signed_hash}",
        "",
        "Signers:",
    ]
    for s in sorted(signers, key=lambda x: x.signer_order):
        lines.append(
            f"  {s.signer_order}. {s.name} <{s.email}> role={s.role} "
            f"opened={s.opened_at} signed={s.signed_at} method={s.signature_type} ip={s.ip_address}"
        )
    lines.append("")
    lines.append("Event timeline:")
    for ev in sorted(events, key=lambda e: e.created_at or datetime.now(timezone.utc)):
        lines.append(f"  - {ev.created_at} {ev.action} actor={ev.actor}")
    lines.append("")
    lines.append(
        "This certificate is for demonstration only and is not a licensed trust-service certificate."
    )
    page.insert_textbox(fitz.Rect(40, y, 555, 800), "\n".join(str(x) for x in lines), fontsize=9)
    out = doc.tobytes()
    doc.close()
    return out
