"""PyMuPDF helpers for signed contract PDF and demo audit certificate."""
from __future__ import annotations

import hashlib
import io
from datetime import datetime, timezone

import fitz

from ..models import Contract, SignatureRequest, SignatureSigner, SignatureEvent
from .storage import storage

DEMO_FOOTER_EN = (
    "Demo electronic signature generated by ContractOps AI. "
    "Not represented as a certified trust-service signature."
)
DEMO_FOOTER_AR = (
    "توقيع إلكتروني تجريبي تم إنشاؤه عبر ContractOps AI، "
    "ولا يُمثّل توقيعًا معتمدًا من مقدم خدمات ثقة مرخص."
)


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def original_bytes(contract: Contract) -> bytes:
    if not contract.file_url:
        return _demo_text_pdf(contract.title or "Contract", contract.raw_text or "")
    raw = storage.get(contract.file_url)
    if raw[:4] == b"%PDF":
        return raw
    text = contract.raw_text or contract.title or "Contract document"
    return _demo_text_pdf(contract.title or "Contract", text)


def _demo_text_pdf(title: str, body: str) -> bytes:
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    page.insert_text((50, 50), title[:200], fontsize=14)
    page.insert_text((50, 80), "Demo PDF representation (original upload was not PDF).", fontsize=10)
    chunk = (body or "")[:8000]
    page.insert_textbox(fitz.Rect(50, 110, 545, 800), chunk, fontsize=9)
    out = doc.tobytes()
    doc.close()
    return out


def _load_signature_image(signer: SignatureSigner) -> bytes | None:
    if not signer.signature_value_url:
        return None
    try:
        return storage.get(signer.signature_value_url)
    except Exception:
        return None


def build_signed_pdf(
    contract: Contract,
    request: SignatureRequest,
    signers: list[SignatureSigner],
) -> bytes:
    base = original_bytes(contract)
    doc = fitz.open(stream=base, filetype="pdf")
    page = doc.new_page(width=595, height=842)
    y = 40
    page.insert_text((40, y), "Signatures / التوقيعات", fontsize=16)
    y += 30
    page.insert_text((40, y), f"Request: {request.id}", fontsize=9)
    y += 24
    for s in sorted(signers, key=lambda x: x.signer_order):
        page.insert_text((40, y), f"{s.signer_order}. {s.name} — {s.role}", fontsize=11)
        y += 16
        if s.signed_at:
            page.insert_text((40, y), f"Signed: {s.signed_at.isoformat()}", fontsize=9)
            y += 14
        img = _load_signature_image(s)
        if img and (img[:4] == b"\x89PNG" or img[:2] == b"\xff\xd8"):
            try:
                rect = fitz.Rect(40, y, 240, y + 60)
                page.insert_image(rect, stream=img)
                y += 70
            except Exception:
                if s.signature_type == "typed" and signer_text_from_storage(s):
                    page.insert_text((40, y), signer_text_from_storage(s) or "", fontsize=14)
                    y += 24
        elif s.signature_type == "typed":
            txt = signer_text_from_storage(s)
            if txt:
                page.insert_text((40, y), txt, fontsize=16)
                y += 28
        y += 10
    y = min(y + 20, 780)
    page.insert_text((40, y), DEMO_FOOTER_EN, fontsize=8)
    page.insert_text((40, y + 14), DEMO_FOOTER_AR, fontsize=8)
    out = doc.tobytes()
    doc.close()
    return out


def signer_text_from_storage(signer: SignatureSigner) -> str | None:
    if signer.signature_type != "typed" or not signer.signature_value_url:
        return None
    try:
        return storage.get(signer.signature_value_url).decode("utf-8")
    except Exception:
        return None


def build_certificate_pdf(
    contract: Contract,
    request: SignatureRequest,
    signers: list[SignatureSigner],
    events: list[SignatureEvent],
    *,
    original_hash: str,
    signed_hash: str,
) -> bytes:
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    y = 40
    page.insert_text((40, y), "Demo Signature Audit Certificate", fontsize=16)
    page.insert_text((40, y + 18), "شهادة سجل توقيع تجريبية", fontsize=14)
    y += 50
    lines = [
        f"Contract: {contract.title}",
        f"Contract ID: {contract.id}",
        f"Signature Request ID: {request.id}",
        f"Provider: {request.provider}",
        f"Created: {request.created_at}",
        f"Sent: {request.sent_at}",
        f"Completed: {request.completed_at}",
        f"Original hash (SHA-256): {original_hash}",
        f"Signed hash (SHA-256): {signed_hash}",
        "",
        "Signers:",
    ]
    for s in sorted(signers, key=lambda x: x.signer_order):
        lines.append(
            f"  {s.signer_order}. {s.name} <{s.email}> role={s.role} "
            f"opened={s.opened_at} signed={s.signed_at} method={s.signature_type} ip={s.ip_address}"
        )
    lines.append("")
    lines.append("Event timeline:")
    for ev in sorted(events, key=lambda e: e.created_at or datetime.now(timezone.utc)):
        lines.append(f"  - {ev.created_at} {ev.action} actor={ev.actor}")
    lines.append("")
    lines.append(
        "This certificate is for demonstration only and is not a licensed trust-service certificate."
    )
    page.insert_textbox(fitz.Rect(40, y, 555, 800), "\n".join(str(x) for x in lines), fontsize=9)
    out = doc.tobytes()
    doc.close()
    return out
